"""
Generates Advanced SubStation Alpha (.ass) subtitle files
with karaoke word-highlighting for FFmpeg's `ass` filter.

Each spoken word gets a `{\\k}` timing tag. Non-spoken (yet) words
are dimmed; the currently-spoken word is highlighted.
"""

import os
from typing import Optional

from app.models.segment import WordTimestamp


def _secs_to_ass_time(seconds: float) -> str:
    """Convert seconds to ASS time format H:MM:SS.cs"""
    total_centiseconds = int(round(seconds * 100))
    h, remainder = divmod(total_centiseconds, 360000)
    m, remainder = divmod(remainder, 6000)
    s, cs = divmod(remainder, 100)
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def _seconds_to_centiseconds(seconds: float) -> int:
    """Convert seconds to ASS centiseconds (1cs = 0.01s)."""
    return max(1, int(round(seconds * 100)))


ASS_STYLES_FORMAT = (
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
    "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
    "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
    "Alignment, MarginL, MarginR, MarginV, Encoding"
)
ASS_STYLE_HIGHLIGHTED = (
    "Style: Highlighted,Arial,48,&H00FFFFFF,&H000000FF,"
    "&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,2,1,2,10,10,30,1"
)
ASS_STYLE_DIMMED = (
    "Style: Dimmed,Arial,48,&H00AAAAAA,&H000000AA,"
    "&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,2,1,2,10,10,30,1"
)

ASS_EVENTS_FORMAT = "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"  # noqa: E501

ASS_HEADER = "\n".join([
    "[Script Info]",
    "; Generated by vidbits",
    "ScriptType: v4.00+",
    "PlayResX: 1080",
    "PlayResY: 1920",
    "ScaledBorderAndShadow: yes",
    "",
    "[V4+ Styles]",
    ASS_STYLES_FORMAT,
    ASS_STYLE_HIGHLIGHTED,
    ASS_STYLE_DIMMED,
    "",
    "[Events]",
    ASS_EVENTS_FORMAT,
    "",
])


def generate_ass(words: list[WordTimestamp], output_path: str, duration: Optional[float] = None) -> str:  # noqa: E501
    """Build an .ass file from word timestamps.

    Each word is rendered as two overlapping Dialogue lines:
      - A dimmed line spanning the full duration (future words)
      - A highlighted line for just that word's duration (karaoke pop)

    This creates the effect of words lighting up as they're spoken.
    """
    if not words:
        _write_empty_ass(output_path)
        return output_path

    end_time = duration or max(w.end for w in words)

    lines = [ASS_HEADER]

    for word in words:
        word_dur_cs = _seconds_to_centiseconds(word.end - word.start)

        # Dimmed (background) — visible for the whole segment
        lines.append(
            f"Dialogue: 0,{_secs_to_ass_time(word.start)},{_secs_to_ass_time(end_time)},"
            f"Dimmed,,0,0,0,,{{\\k{word_dur_cs}}}{word.word}\\N"
        )
        # Highlighted (foreground) — visible only for this word's duration
        lines.append(
            f"Dialogue: 1,{_secs_to_ass_time(word.start)},{_secs_to_ass_time(word.end)},"
            f"Highlighted,,0,0,0,,{{\\k{word_dur_cs}}}{word.word}\\N"
        )

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.writelines(lines)

    return output_path


def _write_empty_ass(output_path: str):
    """Write a minimal valid ASS file for empty word lists."""
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.write(ASS_HEADER)
